// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXbKmyZP_qT6U5E4Jk41OGS2DpaJkiGJ0',
    appId: '1:71835287248:web:3b4ebeab04476e3af768d5',
    messagingSenderId: '71835287248',
    projectId: 'bloodcollect-be2ac',
    authDomain: 'bloodcollect-be2ac.firebaseapp.com',
    storageBucket: 'bloodcollect-be2ac.firebasestorage.app',
    measurementId: 'G-L3TJDC5H7K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYxtChZxX4j_rf1a8glsETGe8Mb1t3ilk',
    appId: '1:71835287248:android:eaa53c8e1b2198b3f768d5',
    messagingSenderId: '71835287248',
    projectId: 'bloodcollect-be2ac',
    storageBucket: 'bloodcollect-be2ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmi-Qv6eUcLZB8Hhqnoewjju0G65zqypA',
    appId: '1:71835287248:ios:0fd17733dd968027f768d5',
    messagingSenderId: '71835287248',
    projectId: 'bloodcollect-be2ac',
    storageBucket: 'bloodcollect-be2ac.firebasestorage.app',
    iosBundleId: 'com.flufithon.bloodCollect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmi-Qv6eUcLZB8Hhqnoewjju0G65zqypA',
    appId: '1:71835287248:ios:0fd17733dd968027f768d5',
    messagingSenderId: '71835287248',
    projectId: 'bloodcollect-be2ac',
    storageBucket: 'bloodcollect-be2ac.firebasestorage.app',
    iosBundleId: 'com.flufithon.bloodCollect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXbKmyZP_qT6U5E4Jk41OGS2DpaJkiGJ0',
    appId: '1:71835287248:web:1c46a7595bd3a8f6f768d5',
    messagingSenderId: '71835287248',
    projectId: 'bloodcollect-be2ac',
    authDomain: 'bloodcollect-be2ac.firebaseapp.com',
    storageBucket: 'bloodcollect-be2ac.firebasestorage.app',
    measurementId: 'G-N47Q4SG6RP',
  );
}
